// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlvATdHf81z3tldYPp2QDCNjcSS56yeAc',
    appId: '1:980066212126:web:9bd669e4a6800ca1c3110f',
    messagingSenderId: '980066212126',
    projectId: 'digitalreceipts2',
    authDomain: 'digitalreceipts2.firebaseapp.com',
    databaseURL: 'https://digitalreceipts2.firebaseio.com',
    storageBucket: 'digitalreceipts2.appspot.com',
    measurementId: 'G-DDQBR3V39M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedbEQCuCJg4p24IoVPsQdwS5DdJEulg8',
    appId: '1:980066212126:android:cb4991ddc44cd572c3110f',
    messagingSenderId: '980066212126',
    projectId: 'digitalreceipts2',
    databaseURL: 'https://digitalreceipts2.firebaseio.com',
    storageBucket: 'digitalreceipts2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8blpP-ztAYmt5yo93p0b61JevkQUXhKc',
    appId: '1:980066212126:ios:db33f15beda0c21ec3110f',
    messagingSenderId: '980066212126',
    projectId: 'digitalreceipts2',
    databaseURL: 'https://digitalreceipts2.firebaseio.com',
    storageBucket: 'digitalreceipts2.appspot.com',
    androidClientId: '980066212126-126b9asi40fhrr81b7pq02c5lntfvteq.apps.googleusercontent.com',
    iosClientId: '980066212126-0rtid7mk0no682qnapaqh5dtvfo39en8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTest1',
  );
}
